---
- name: new home pi
  hosts: all
  become: yes

  tasks:
    # GARBAGE PERFORMANCE - GARBAGE GARBAGE GARBAGE GARBAGE!
    # - name: Run samba
    #   docker_container:
    #     name: samba
    #     image: dastrasmue/rpi-samba:v3
    #     pull: true
    #     published_ports:
    #       - "137:137/udp"
    #       - "138:138/udp"
    #       - "139:139"
    #       - "445:445"
    #     state: started
    #     restart_policy: unless-stopped
    #     env:
    #         TZ: PDT
    #     volumes:
    #       - /data/nas:/data
    #     command: -u "nas:nas" -s "data:/data:rw:nas"

    # echo "/data 192.168.0.0/255.255.255.0(rw,insecure,all_squash,anonuid=65534,anongid=65534)" >> /etc/exports
    # sudo mount -o rw -t nfs 192.168.0.253:/data /Volumes/nas
  - name: NFS server
    docker_container:
      name: nfs
      image: nunofgs/rpi-nfs
      pull: true
      published_ports:
        - "111:111"
        - "111:111/udp"
        - "2049:2049"
        - "2049:2049/udp"
      state: started
      restart_policy: unless-stopped
      volumes:
        - /data/nas:/data
