---
- name: new home pi
  hosts: all
  become: yes

  tasks:
    - name: Run samba
      docker_container:
        name: samba
        image: dastrasmue/rpi-samba:v3
        pull: true
        published_ports:
          - "137:137/udp"
          - "138:138/udp"
          - "139:139"
          - "445:445"
        state: started
        restart_policy: unless-stopped
        env:
            TZ: PDT
        volumes:
          - /data/nas:/data
        command: -u "nas:nas" -s "data:/data:rw:nas"
