---
- name: new home pi
  hosts: all
  become: yes

  vars:
    packages_to_install: [ python-pip, hfsplus, hfsutils, hfsprogs, mc, vim ]
    pip_packages_to_install: [ docker-py ]
    update_cache: no

  roles:
    - mivok0.users
    - raspbian-docker

  tasks:
    - name: 'Update APT package cache'
      action: apt update_cache=yes

    - name: 'Upgrade APT to the lastest packages'
      action: apt upgrade=safe

    - name: 'Install some packages'
      apt: pkg="{{ item }}" state=installed update_cache="{{ update_cache }}"
      with_items: "{{ packages_to_install }}"

    # See https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=126338
    - name: 'Upgrade pip'
      shell: easy_install --upgrade pip

    - name: 'Install python modules'
      pip: name="{{ item }}"
      with_items: "{{ pip_packages_to_install }}"

    - name: Enable passwordless sudo
      action: 'lineinfile dest=/etc/sudoers regexp="^psbrandt" line="psbrandt ALL=(ALL:ALL) NOPASSWD: ALL" state=present'

    - name: 'Disallow password authentication'
      action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present

    - name: 'Configure WIFI'
      copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

    - name: 'Mount USB device by UUID'
      mount:
        name: /data
        src: UUID=da78fd67-460e-4f5a-b364-b93666fa8124
        fstype: ext4
        state: mounted

    # nobody:nogroup is required for public writable samba share
    - name: 'Set data drive access'
      file:
        path: /data/nas
        state: directory
        owner: nobody
        group: nogroup
        recurse: yes
        mode: u=rwx,g=rwx

    - name: 'Initiate reboot'
      command: sleep 2 && reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: 'Wait for reboot'
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=10
      become: false
